name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn

      - run: yarn nx format:check
      - run: yarn nx affected -t lint --parallel=3
      - run: yarn nx affected -t test --parallel=3 --configuration=ci
      - run: yarn nx affected -t build --parallel=3
