name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .node-version

      - name: Set Shas
        uses: nrwl/nx-set-shas@v3

      - name: Yarn
        run: yarn

      - name: Format Check
        run: yarn nx format:check

      - name: Lint
        run: yarn nx affected -t lint --parallel=3

      - name: Test
        run: yarn nx affected -t test --parallel=3 --configuration=ci

      - name: Build
        run: yarn nx affected -t build --parallel=3
