name: NPM Publish @brimdata/zed-wasm
on:
  push:
    branches:
      - main
    paths:
      - packages/zed-wasm/package.json

jobs:
  publish:
    name: Publish @brimdata/zed-wasm to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .node-version

      - name: Yarn
        run: yarn

      - name: Test Zed Wasm
        run: yarn nx run-many --targets=lint,test,build --projects=zed-wasm

      - name: Publish To NPM
        id: npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './dist/packages/zed-wasm/package.json'

      - name: Notify Slack
        if: steps.npm.outputs.type != 'none'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: '{"text": "Published @brimdata/zed-wasm version ${{ steps.npm.outputs.version }}\nhttps://www.npmjs.com/package/@brimdata/zed-wasm"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
